from flask import Flask
from flask_restful import Api

from items import *

app = Flask(__name__)
api = Api(app)

api.add_resource(Zero, '/zero/<string:name>')
api.add_resource(AnywayCompany, '/anyway/<string:name>')
api.add_resource(Awesome, '/awesome')
api.add_resource(Asshole, '/asshole')
api.add_resource(Backoff, '/backoff/<string:name>')
api.add_resource(BallmerCompany, '/ballmercompany/<string:company>/<string:name>')
api.add_resource(Bag, '/bag')
api.add_resource(Bday, '/bday/<string:name>')
api.add_resource(Blackadder, '/blackadder/<string:name>')
api.add_resource(Bravo, '/bravo/<string:name>')
api.add_resource(Why, '/why')
api.add_resource(Bucket, '/bucket')
api.add_resource(Bye, '/bye')
api.add_resource(Bus, '/bus/<string:name>')
api.add_resource(CanIUse, '/caniuse/<string:tool>')
api.add_resource(Chainsaw, '/chainsaw/<string:name>')
api.add_resource(Worthless, '/worthless/<string:name>')
api.add_resource(Hypocritical, '/hyposcritical/<string:name>')
api.add_resource(Donut, '/donut/<string:name>')
api.add_resource(DoSomething, '/dosomething/<string:do>/<string:something>')
api.add_resource(Equity, '/equity/<string:name>')
api.add_resource(CantEven, '/canteven/<string:thing>')
api.add_resource(Fascinating, '/fascinating/<string:name>')
api.add_resource(Cool, '/cool')
api.add_resource(Cup, '/cup')
api.add_resource(Chat, '/chat')
api.add_resource(Everyone, '/everyone')
api.add_resource(Everything, '/everything')
api.add_resource(Fever, '/fever/<string:name>')
api.add_resource(Horse, '/fever/<string:name>')
api.add_resource(Keep, '/keep/<string:name>')
api.add_resource(King, '/king/<string:name>')
api.add_resource(Foreign, '/foreign/<string:name>')
api.add_resource(Look, '/look/<string:name>')
api.add_resource(Insane, '/insane/<string:name>')
api.add_resource(Nugget, '/nugget/<string:name>')
api.add_resource(Outside, '/outside/<string:name>')
api.add_resource(Shakespeare, '/shakespeare/<string:name>')
api.add_resource(Time, '/time/<string:name>')
api.add_resource(Calm, '/calm/<string:reaction>')
api.add_resource(Particular, '/particular/<string:thing>')
api.add_resource(Language, '/language/<string:lang>')
api.add_resource(Family, '/family')
api.add_resource(Flying, '/flying')
api.add_resource(Ftfy, '/ftfy')
api.add_resource(FTS, '/fts')
api.add_resource(Holygrail, '/holygrail')
api.add_resource(Immensity, '/immensity')
api.add_resource(Looking, '/looking')
api.add_resource(Maybe, '/maybe')
api.add_resource(No, '/no')
api.add_resource(Programmer, '/programmer')
api.add_resource(Rat, '/rat')
api.add_resource(Thumbs, '/thumbs')


if __name__ == "__main__":
    app.run(port=5000, debug=True)
